### ISSUE TITLE
Support for cluster mode

### ISSUE THREAD

**Issue by anis028** [yannh/redis-dump-go#13]
How can I take backup for redis running on `cluster` mode using redis-dump-go?

**Comment by yannh** [comment]
Hi @anis028 , I haven't looked into this - I assume it doesnt work right now? What error are you seeing?

**Comment by anis028** [comment]
Not error actually. But i am not sure how to manage it. if i run redis-dump-go on a master of a cluster, it writes only the keys that are stored in that master. so, when restoring it becomes a problem. if I feed the dump.resp file to a master if the slots of the keys are not currently served by this master, it gives error. only the keys that falls under the current master is restored. so if a dump file has key with slots that are currently split between masters, it becomes redundant operation.

**Comment by yannh** [comment]
@anis028 https://redislabs.com/redis-enterprise/technology/backup-disaster-recovery/  seems to indicate backing up individual shards? I am not very familiar with backups of redis clusters unfortunately.

**Comment by anis028** [comment]
@yannh i think that is the process in which the dump.rdb and appendonly.aof files are used. They are the part of redis persistence. But I was trying to do with your redis-dump-go project, and was wondering if you guys did something for backup of clustering mode.

**Comment by yannh** [comment]
No, redis-dump-go has never been tested to work on Clustered Redis (yet).

**Comment by anis028** [comment]
Do you guys have any plans for incorporating the feature of redis cluster backup in near future?

**Comment by yannh** [comment]
No, though I would probably accept patches going in that direction... Right now I am not sure what would be required.

**Comment by yannh** [comment]
Closing for now!

**Comment by Shaad7** [comment]
Any update about this ? Is redis-dump-go tested for redis cluster mode ?
