### ISSUE TITLE
Got connection reset by peer while the restoring in the middle of the progress

### ISSUE THREAD

**Issue by peidong-hu** [yannh/redis-dump-go#3]
redis-cli -h platform-test-small-redis-redis-ha.platform-test-small.svc.cluster.local --pipe < redis-backup.resp
Error reading from the server: Connection reset by peer

**Comment by yannh** [comment]
Hi Peidong!  Can you connect to your server from the same host using redis-cli? If yes, try flushing and importing again?

**Comment by peidong-hu** [comment]
Hi,

I think I got the reason is the out of memory on the media server. We can
close it now.

Peidong
