### ISSUE TITLE
Auth issues with the latest build

### ISSUE THREAD

**Issue by samitpal** [yannh/redis-dump-go#35]
I'm getting authentication error with the latest build. It was working fine with version 0.5.1.
Seems like [getDBIndexes](https://github.com/yannh/redis-dump-go/blob/master/pkg/redisdump/redisdump.go#L266) function is not using the password. Can the auth error be because of that?

**Comment by yannh** [comment]
I will look into this very soon and add tests around it :)

**Comment by yannh** [comment]
I've pushed a fix - repeats some code but should work :) I also added an acceptance test to test connections with a password. As soon as Github actions works again I'll publish a new release :+1:

**Comment by yannh** [comment]
Alright code should now be nicer and avoid unnecessary duplication... and the bug is fixed, as attested by the new acceptance tests :) Tagged v0.7.0
