### ISSUE TITLE
dump all dbs doesn't work

### ISSUE THREAD

**Issue by konstantin-schura** [yannh/redis-dump-go#37]
Hello,

redis-server 5.0.9
redis-dump-go v0.7.0

Dump and restore all dbs doesn't work. All dbs (3,5,7) restoring to 0 db.

before restore:
# Keyspace
db0:keys=280317,expires=279847,avg_ttl=208563507
db7:keys=8927,expires=0,avg_ttl=0

backup:
REDISDUMPGO_AUTH=pass redis-dump-go -port 6379 -host 127.0.0.1 -n 100 > redis.dump
REDISDUMPGO_AUTH=pass redis-cli -c -h 127.0.0.1 -p 6379 --pipe  < redis.dump

after restore:
# Keyspace
db0:keys=289432,expires=280032,avg_ttl=214048507

Is it normal behaviour now?

Thanks.

**Comment by yannh** [comment]
Hi @konstantin-schura , indeed, I added an acceptance test in a new branch, it looks like the selects are missing during the dump. Working on a fix.

**Comment by yannh** [comment]
Pushed 0.7.1! Now with an acceptance test it should not break again. Thanks for the report :bow:
