### ISSUE TITLE
Any plan to upgrade `radix` version to `v4` ?

### ISSUE THREAD

**Issue by hossainemruz** [yannh/redis-dump-go#40]

**Comment by yannh** [comment]
Hi, i didn't know there was a v4 :) Any specific functionality you're looking forward to?

**Comment by hossainemruz** [comment]
No. I have also just discovered that there is v4 and v3 is now maintenance mode only. I tried upgrading my fork to v4 but it seems lots of changes are necessary. :(

**Comment by yannh** [comment]
You're not selling it well :rofl: I might look at it at some point but unless there are clear benefits, it might take a little bit of time. I'd accept a PR though :bow:

**Comment by hossainemruz** [comment]
Haha! I will definitely send a PR if I find any obvious reason to upgrade.
