### ISSUE TITLE
Please add a shell to the docker-image or an option to specify output file

### ISSUE THREAD

**Issue by pamelia** [yannh/redis-dump-go#45]
We do backups with cronjob in kubernetes like this:

command: ['bash', '-c', '/redis-dump-go -host redis > /backup/redis.resp']

The docker-image you provide doesn't have a shell only the binary and you don't provide an option to specify output file..

**Comment by yannh** [comment]
Hi @pamelia , I provide two different flavors of the docker image, some come with alpine: https://github.com/yannh/redis-dump-go/pkgs/container/redis-dump-go , eg  0.8.0-alpine . Alpine itself doesn't come with bash, but does have a shell, eg /bin/sh , with which you should be able to do what you want :+1:
