### ISSUE TITLE
Support for Redis Cluster Mode

### ISSUE THREAD

**Issue by AbdullahAlShaad** [yannh/redis-dump-go#46]
I have tried to take backup when Redis is running in Cluster Mode. The backup only contains data from one shard. To be precise, when the `scan` command is run, it only list the data from one node in the shard.

Is there any workaround using which I can take backup when Redis is running in Cluster Mode ?

**Comment by yannh** [comment]
This is currently not supported. I don't use redis-cluster either, so it's not on top of my todo list unfortunately :grimacing:
