### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by kmmndr** [yannh/redis-dump-go#6]
Hi Yann,

Thanks for `redis-dump-go`, that's a nice tool. But it could be even nicer properly packaged in all of our favorites distributions :-)

Could you please create a tag or release a first version of the project ?

Best regards

**Comment by yannh** [comment]
Hi @kmmndr ! Yes I can do that ! What are you planning to package this for? Anything else I can do to help?

**Comment by yannh** [comment]
Update: I added a simple goreleaser config and will do Github releases from now on.
