### ISSUE TITLE
Support for dump one database?

### ISSUE THREAD

**Issue by linydquantil** [yannh/redis-dump-go#8]
for example:
-d DB  dump DATABASE (0-N, default 0)

**Comment by yannh** [comment]
That should be pretty trivial to implement, I will look into this soon!

**Comment by linydquantil** [comment]
ok, thank you ,good job

**Comment by yannh** [comment]
No no leave it open, I ll forget otherwise :)

**Comment by yannh** [comment]
I implemented that with -db, the default being to dump all databases for backwards compatibility. 
Also fixed a couple of bugs - made a new release v0.3.2 , try it out!
